In [13]:
import pandas as pd
import numpy as np


In [14]:
np.version


<module 'numpy.version' from 'C:\\Users\\desktop\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [15]:
np.nan

nan

In [16]:
l1=[1,2,3,4]

In [17]:
type(l1)

list

In [18]:
x=np.array(l1)

In [19]:
x

array([1, 2, 3, 4])

In [20]:
type(x)

numpy.ndarray

In [21]:
np.array([1,3,5,7])

array([1, 3, 5, 7])

In [22]:
data1=np.array([1, None,2,3])

In [23]:
data1

array([1, None, 2, 3], dtype=object)

In [29]:
%timeit np.arange(1E6,dtype=int).sum()

2.32 ms ± 104 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [30]:
%timeit np.arange(1E6,dtype=object).sum()

89.2 ms ± 1.98 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
data2= np.array([18,np.nan,30,4])

In [32]:
data2

array([18., nan, 30.,  4.])

In [33]:
type(data2)

numpy.ndarray

In [34]:
1+np.nan

nan

In [36]:
11*np.nan

nan

# Nan and None:-

In [45]:
pd.Series([1,5,np.nan,'a',None,0])

0       1
1       5
2     NaN
3       a
4    None
5       0
dtype: object

In [46]:
x= pd.Series(range(2), dtype=int)

In [47]:
x

0    0
1    1
dtype: int32

In [48]:
x[1]=None

In [49]:
x

0    0.0
1    NaN
dtype: float64

In [74]:
y = pd.Series(range(7), dtype=object)

In [75]:
y


0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: object

In [76]:
y[5]=None
y[1]=np.nan


In [77]:
y

0       0
1     NaN
2       2
3       3
4       4
5    None
6       6
dtype: object

In [70]:
y = pd.Series(range(5), dtype=int)

In [71]:
y

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [72]:
y[3]=None
y[2]=np.nan

In [73]:
y

0    0.0
1    1.0
2    NaN
3    NaN
4    4.0
dtype: float64

In [82]:
y = pd.Series(range(5), dtype=float)

In [83]:
y

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [84]:
y[4]=None

In [85]:
y

0    0.0
1    1.0
2    2.0
3    3.0
4    NaN
dtype: float64

In [86]:
y[5]=np.nan

In [87]:
y

0    0.0
1    1.0
2    2.0
3    3.0
4    NaN
5    NaN
dtype: float64

In [78]:
y = pd.Series(range(5), dtype=bool)

In [79]:
y

0    False
1     True
2     True
3     True
4     True
dtype: bool

In [80]:
y[2]=np.nan
y[3]=None

In [81]:
y

0    False
1     True
2      NaN
3     None
4     True
dtype: object

# Pandas nullable dtypes:-

In [88]:
df=pd.read_csv("C:/Users/desktop/Downloads/netflix_data.csv")

In [89]:
df

show_id     type                                    title  \
0         s1  TV Show                                       3%   
1         s2    Movie                                     7:19   
2         s3    Movie                                    23:59   
3         s4    Movie                                        9   
4         s5    Movie                                       21   
...      ...      ...                                      ...   
7782   s7783    Movie                                     Zozo   
7783   s7784    Movie                                   Zubaan   
7784   s7785    Movie                        Zulu Man in Japan   
7785   s7786  TV Show                    Zumbo's Just Desserts   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...   
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...   
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
...                 ...                                                ...   
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784                NaN                                            Nasty C   
7785                NaN                         Adriano Zumbo, Rachel Khoo   
7786           Sam Dunn                                                NaN   

             country          date_added  release_year  duration  \
0             Brazil     August 14, 2020          2020         4   
1             Mexico   December 23, 2016          2016        93   
2          Singapore   December 20, 2018          2011        78   
3      United States   November 16, 2017          2009        80   
4      United States     January 1, 2020          2008       123   
...              ...                 ...           ...       ...   
7782          Sweden    October 19, 2020          2005        99   
7783           India       March 2, 2019          2015       111   
7784             NaN  September 25, 2020          2019        44   
7785       Australia    October 31, 2020          2019         1   
7786  United Kingdom       March 1, 2020          2019        90   

                                            description             genre  
0     In a future where the elite inhabit an island ...  International TV  
1     After a devastating earthquake hits Mexico Cit...            Dramas  
2     When an army recruit is found dead, his fellow...     Horror Movies  
3     In a postapocalyptic world, rag-doll robots hi...            Action  
4     A brilliant group of students become card-coun...            Dramas  
...                                                 ...               ...  
7782  When Lebanon's Civil War deprives Zozo of his ...            Dramas  
7783  A scrappy but poor boy worms his way into a ty...            Dramas  
7784  In this documentary, South African rapper Nast...     Documentaries  
7785  Dessert wizard Adriano Zumbo looks for the nex...  International TV  
7786  This documentary delves into the mystique behi...     Documentaries  

[7787 rows x 11 columns]

In [107]:
df.head()

show_id     type  title           director  \
0      s1  TV Show     3%                NaN   
1      s2    Movie   7:19  Jorge Michel Grau   
2      s3    Movie  23:59       Gilbert Chan   
3      s4    Movie      9        Shane Acker   
4      s5    Movie     21     Robert Luketic   

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   

          date_added  release_year  duration  \
0    August 14, 2020          2020         4   
1  December 23, 2016          2016        93   
2  December 20, 2018          2011        78   
3  November 16, 2017          2009        80   
4    January 1, 2020          2008       123   

                                         description             genre  
0  In a future where the elite inhabit an island ...  International TV  
1  After a devastating earthquake hits Mexico Cit...            Dramas  
2  When an army recruit is found dead, his fellow...     Horror Movies  
3  In a postapocalyptic world, rag-doll robots hi...            Action  
4  A brilliant group of students become card-coun...            Dramas

In [108]:
df.tail()

show_id     type                                    title     director  \
7782   s7783    Movie                                     Zozo  Josef Fares   
7783   s7784    Movie                                   Zubaan  Mozez Singh   
7784   s7785    Movie                        Zulu Man in Japan          NaN   
7785   s7786  TV Show                    Zumbo's Just Desserts          NaN   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS     Sam Dunn   

                                                   cast         country  \
7782  Imad Creidi, Antoinette Turk, Elias Gergi, Car...          Sweden   
7783  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...           India   
7784                                            Nasty C             NaN   
7785                         Adriano Zumbo, Rachel Khoo       Australia   
7786                                                NaN  United Kingdom   

              date_added  release_year  duration  \
7782    October 19, 2020          2005        99   
7783       March 2, 2019          2015       111   
7784  September 25, 2020          2019        44   
7785    October 31, 2020          2019         1   
7786       March 1, 2020          2019        90   

                                            description             genre  
7782  When Lebanon's Civil War deprives Zozo of his ...            Dramas  
7783  A scrappy but poor boy worms his way into a ty...            Dramas  
7784  In this documentary, South African rapper Nast...     Documentaries  
7785  Dessert wizard Adriano Zumbo looks for the nex...  International TV  
7786  This documentary delves into the mystique behi...     Documentaries

In [102]:
df.describe()

release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

In [103]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'duration', 'description', 'genre'],
      dtype='object')

In [104]:
df.director.isnull()

0        True
1       False
2       False
3       False
4       False
        ...  
7782    False
7783    False
7784     True
7785     True
7786    False
Name: director, Length: 7787, dtype: bool

In [105]:
df.country.notnull()

0        True
1        True
2        True
3        True
4        True
        ...  
7782     True
7783     True
7784    False
7785     True
7786     True
Name: country, Length: 7787, dtype: bool

In [106]:
df.genre.value_counts()

genre
Dramas                  1384
Comedies                1074
Documentaries            751
Action                   721
International TV         690
Children                 502
Crime TV                 369
Kids                     359
Stand-Up                 354
Horror Movies            244
British TV               232
Docuseries               194
Anime Series             148
International Movies     114
TV Comedies              110
Reality TV               102
Classic Movies            77
TV Dramas                 62
Uncategorized             56
Thrillers                 49
TV Action                 37
Romantic TV               28
Classic                   21
Independent Movies        20
Anime Features            19
Music                     17
TV Shows                  12
Cult Movies               12
Sci-Fi                    11
TV Horror                 10
Romantic Movies            3
Spanish-Language           2
Sports Movies              1
TV Sci                     1
LGBTQ Mo

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64 
 8   duration      7787 non-null   int64 
 9   description   7787 non-null   object
 10  genre         7787 non-null   object
dtypes: int64(2), object(9)
memory usage: 669.3+ KB


In [110]:
df.isnull()

show_id   type  title  director   cast  country  date_added  \
0       False  False  False      True  False    False       False   
1       False  False  False     False  False    False       False   
2       False  False  False     False  False    False       False   
3       False  False  False     False  False    False       False   
4       False  False  False     False  False    False       False   
...       ...    ...    ...       ...    ...      ...         ...   
7782    False  False  False     False  False    False       False   
7783    False  False  False     False  False    False       False   
7784    False  False  False      True  False     True       False   
7785    False  False  False      True  False    False       False   
7786    False  False  False     False   True    False       False   

      release_year  duration  description  genre  
0            False     False        False  False  
1            False     False        False  False  
2            False     False        False  False  
3            False     False        False  False  
4            False     False        False  False  
...            ...       ...          ...    ...  
7782         False     False        False  False  
7783         False     False        False  False  
7784         False     False        False  False  
7785         False     False        False  False  
7786         False     False        False  False  

[7787 rows x 11 columns]